/*
 * Taken from /e/OS Assistant
 *
 * Copyright (C) 2024 MURENA SAS
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.stypox.dicio.io.input.vosk

import android.util.Log
import org.json.JSONException
import org.json.JSONObject
import org.stypox.dicio.io.input.InputEvent
import org.stypox.dicio.io.session.CarfuLog
import org.stypox.dicio.io.session.CommandEndpointPolicy
import org.stypox.dicio.io.session.CommandSession
import org.stypox.dicio.io.session.EmptyEndpointAction
import org.stypox.dicio.io.session.VietnameseTranscript
import org.vosk.android.RecognitionListener


/**
 * This class is an implementation of [RecognitionListener] that listens to events generated by
 * command capture (shared PCM hub or fallback AudioRecord), pushes them to [eventListener],
 * and handles the listening state via [VoskInputDevice].
 *
 * @param silencesBeforeStop how many times Vosk should report a "silence" before giving up trying
 * to get speech; must be `>= 1`, and setting this to 1 is equivalent to disabling this feature
 */
internal class VoskListener(
    private val voskInputDevice: VoskInputDevice,
    private val eventListener: (InputEvent) -> Unit,
    silencesBeforeStop: Int,
) : RecognitionListener {

    private val endpoint = CommandEndpointPolicy(silencesBeforeStop)
    private var firstCallback = true

    init {
        endpoint.onListeningStarted()
    }

    /**
     * Called when partial recognition result is available.
     */
    override fun onPartialResult(s: String) {
        logFirstCallback("partial")

        var partialInput: String? = null
        try {
            partialInput = JSONObject(s).getString("partial")
        } catch (e: JSONException) {
            Log.e(TAG, "Can't obtain partial result from $s", e)
        }

        partialInput?.also {
            if (it.isNotBlank()) {
                endpoint.onNonEmptyPartial()
                CarfuLog.i(CommandSession.TAG, "PARTIAL_TEXT text=${it.take(80)}")
                eventListener(InputEvent.Partial(it))
            }
        }
    }

    /**
     * Called after silence occurred.
     */
    @Suppress("ktlint:Style:NestedBlockDepth")
    override fun onResult(s: String) {
        logFirstCallback("result")

        // collect all alternative user inputs generated by the STT model
        val inputs = try {
            val jsonResult = JSONObject(s)
            utterancesFromJson(jsonResult)
        } catch (e: JSONException) {
            Log.e(TAG, "Can't obtain result from $s", e)
            eventListener(InputEvent.Error(e))
            voskInputDevice.stopListening(eventListener, false)
            return
        }

        if (inputs.isEmpty() || VietnameseTranscript.isTooWeakToSubmit(inputs[0].first)) {
            when (endpoint.onEmptyOrWeakResult()) {
                EmptyEndpointAction.IGNORE -> {
                    CarfuLog.i(
                        CommandSession.TAG,
                        "SILENCE ignored reason=endpoint_grace leftover=${endpoint.remaining}",
                    )
                    return
                }
                EmptyEndpointAction.COUNT -> {
                    CarfuLog.i(
                        CommandSession.TAG,
                        "SILENCE counted leftover=${endpoint.remaining} reason=weak_or_empty",
                    )
                    return
                }
                EmptyEndpointAction.STOP -> {
                    CarfuLog.i(
                        CommandSession.TAG,
                        "FINAL_TEXT rejected reason=silence_or_weak leftover=0",
                    )
                    voskInputDevice.stopListening(eventListener, false)
                    eventListener(InputEvent.None)
                    return
                }
            }
        }

        CarfuLog.i(
            CommandSession.TAG,
            "FINAL_TEXT text=${inputs[0].first.take(80)} leftover=${endpoint.remaining}",
        )

        // we only want to listen one sentence at a time
        voskInputDevice.stopListening(eventListener, false)

        eventListener(InputEvent.Final(inputs))
    }

    private fun utterancesFromJson(jsonResult: JSONObject): List<Pair<String, Float>> {
        return jsonResult.optJSONArray("alternatives")
            ?.takeIf { array -> array.length() > 0 }
            ?.let { array ->
                val maxConfidence = array.optJSONObject(0)?.optDouble("confidence")?.toFloat()
                    ?: return@let null

                return (0 until array.length())
                    .mapNotNull { i -> array.optJSONObject(i) }
                    .map {
                        Pair(
                            // for some reason the texts returned by Vosk start with " "
                            it.getString("text").removePrefix(" "),
                            // the values for confidence provided by Vosk are not from 0.0 to 1.0
                            it.getDouble("confidence").toFloat() / maxConfidence
                        )
                    }
                    // empty results are not real results, so filter them out so that the listener
                    // will be sent an "InputEvent.None" instead of a ".Final" with empty utterances
                    .filter { it.first.isNotBlank() }
            }
            ?: (jsonResult.optString("text")
                .takeIf { it.isNotBlank() }
                ?.let { listOf(Pair(it.removePrefix(" "), 1.0f)) })
            ?: listOf()
    }

    /**
     * Called after stream end. In our case, always called after silence occurred, since we call
     * stopListening in onResult.
     */
    override fun onFinalResult(s: String) {
        Log.d(TAG, "onFinalResult called with s = $s")
    }
    
    /**
     * Called when an error occurs.
     */
    override fun onTimeout() {
        CarfuLog.i(CommandSession.TAG, "FINAL_TEXT rejected reason=timeout")
        voskInputDevice.stopListening(eventListener, true)
    }

    override fun onError(e: Exception) {
        CarfuLog.e(CommandSession.TAG, "COMMAND_CAPTURE_ERROR ${e.javaClass.simpleName}")
        voskInputDevice.stopListening(eventListener, false)
        eventListener(InputEvent.Error(e))
    }

    private fun logFirstCallback(kind: String) {
        if (!firstCallback) return
        firstCallback = false
        CarfuLog.i(CommandSession.TAG, "FIRST_PCM received=true via=$kind")
    }

    companion object {
        private val TAG = VoskListener::class.simpleName
    }
}
